apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  creationTimestamp: '2019-11-02T06:43:03Z'
  generation: 2
  labels:
    app: Element
  name: Element
  namespace: Element
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: Element
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Element
    spec:
      containers:
        - image: 'registry-vpc.cn-shanghai.aliyuncs.com/wzyuchen/Element:latest'
          imagePullPolicy: Always
          name: Element
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-uf6gtmhishceu658flynw
  creationTimestamp: '2019-11-02T07:16:00Z'
  name: Element-svc
  namespace: Element
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 80
    - name: http1
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: Element
  sessionAffinity: None
  type: LoadBalancer
